import { Inter, Nunito, Allura, Petit_Formal_Script, Playfair_Display } from 'next/font/google'

import './globals.css'
const nunito = Nunito({ subsets: ['latin'], weight: ['300', '400', '600', '700', '800', '900'] })
const allura = Allura({ subsets: ['latin'], weight: ['400'] })
const petitFormalScript = Petit_Formal_Script({ subsets: ['latin'], weight: ['400'] })
const playfairDisplay = Playfair_Display({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${playfairDisplay.className} `}>{children}</body>
    </html>
  )
}
